//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cursed_Market_Reborn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cursed_Market_Reborn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CROSSHAIR_DEFAULT_CIRCLE {
            get {
                object obj = ResourceManager.GetObject("CROSSHAIR_DEFAULT_CIRCLE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CROSSHAIR_DEFAULT_CIRCLE_WHITE {
            get {
                object obj = ResourceManager.GetObject("CROSSHAIR_DEFAULT_CIRCLE_WHITE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon_loading_1 {
            get {
                object obj = ResourceManager.GetObject("icon_loading_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon_loading_2 {
            get {
                object obj = ResourceManager.GetObject("icon_loading_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon_loading_3 {
            get {
                object obj = ResourceManager.GetObject("icon_loading_3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon_overlay {
            get {
                object obj = ResourceManager.GetObject("icon_overlay", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon_settings {
            get {
                object obj = ResourceManager.GetObject("icon_settings", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_SMALL_AURIC {
            get {
                object obj = ResourceManager.GetObject("ICON_SMALL_AURIC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_SMALL_BLOODPOINTS {
            get {
                object obj = ResourceManager.GetObject("ICON_SMALL_BLOODPOINTS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_SMALL_SETTINGS_BLACK {
            get {
                object obj = ResourceManager.GetObject("ICON_SMALL_SETTINGS_BLACK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_SMALL_SETTINGS_WHITE {
            get {
                object obj = ResourceManager.GetObject("ICON_SMALL_SETTINGS_WHITE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_SMALL_SHARDS {
            get {
                object obj = ResourceManager.GetObject("ICON_SMALL_SHARDS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon_tray {
            get {
                object obj = ResourceManager.GetObject("icon_tray", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IMG_LOGO_BIG_BLACK {
            get {
                object obj = ResourceManager.GetObject("IMG_LOGO_BIG_BLACK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IMG_LOGO_BIG_WHITE {
            get {
                object obj = ResourceManager.GetObject("IMG_LOGO_BIG_WHITE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;code&quot;:200,&quot;message&quot;:&quot;OK&quot;,&quot;data&quot;:{&quot;playerId&quot;:&quot;OFFLINE Cursed Market 28.08.2021&quot;,&quot;comment&quot;:&quot;Please, respect other people work and don&apos;t forget to mention Cursed Market creator when sharing - Cranch&quot;,&quot;inventory&quot;:[{&quot;lastUpdateAt&quot;:1617205542,&quot;objectId&quot;:&quot;GE_002&quot;,&quot;quantity&quot;:1},{&quot;lastUpdateAt&quot;:1617205542,&quot;objectId&quot;:&quot;GE_001&quot;,&quot;quantity&quot;:1},{&quot;lastUpdateAt&quot;:1617205542,&quot;objectId&quot;:&quot;S28_Legs007&quot;,&quot;quantity&quot;:1},{&quot;lastUpdateAt&quot;:1617205542,&quot;objectId&quot;:&quot;S28_Torso007&quot;,&quot;quantity&quot;:1},{&quot;lastUpdateAt&quot;:1617205542,&quot;objectId&quot;:&quot;S28_He [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OFFLINERESOURCE_MARKET {
            get {
                return ResourceManager.GetString("OFFLINERESOURCE_MARKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;playerUId&quot;:&quot;NONE&quot;,&quot;selectedCamperIndex&quot;:14,&quot;selectedSlasherIndex&quot;:268435456,&quot;firstTimePlaying&quot;:false,&quot;consecutiveMatchStreak&quot;:1,&quot;currentSeasonTicks&quot;:0,&quot;lastConnectedCharacterIndex&quot;:8,&quot;disconnectPenaltyTime&quot;:&quot;0001-01-01T02:00:00Z&quot;,&quot;lastMatchEndTime&quot;:&quot;2021-06-28T09:01:08.631Z&quot;,&quot;lastMatchStartTime&quot;:&quot;0001-01-01T00:00:00Z&quot;,&quot;lastKillerMatchEndTime&quot;:&quot;0001-01-01T00:00:00Z&quot;,&quot;lastSurvivorMatchEndTime&quot;:&quot;2021-06-28T09:01:08.631Z&quot;,&quot;ongoingGameTime&quot;:&quot;0001-01-01T00:00:00Z&quot;,&quot;cumulativeMatches&quot;:2,&quot;cumulativeMatchesAsSurvi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OFFLINERESOURCE_SAVEFILE {
            get {
                return ResourceManager.GetString("OFFLINERESOURCE_SAVEFILE", resourceCulture);
            }
        }
    }
}
